name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The path to your CLA document
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: '.github/signatures/cla.json'
          path-to-document: 'https://github.com/murtaza-nasir/speakr/blob/master/CLA.md'
          # Branch where signatures will be stored
          branch: 'cla-signatures'
          allowlist: 'bot*,dependabot*,*[bot]'

          # Message shown to contributors
          remote-organization-name: 'murtaza-nasir'
          remote-repository-name: 'speakr'
          create-file-commit-message: 'Creating CLA signature file for storing CLA signatures'
          signed-commit-message: '$contributorName has signed the CLA in #$pullRequestNo'
          custom-notsigned-prcomment: 'Thank you for your contribution! Before we can merge this PR, we need you to sign our Contributor License Agreement (CLA).<br/><br/>Please review the CLA here: [CLA.md](https://github.com/murtaza-nasir/speakr/blob/master/CLA.md)<br/><br/>To sign the CLA, please comment on this PR with:<br/>`I have read the CLA Document and I hereby sign the CLA`<br/><br/>This is a one-time requirement. Once you sign, all your future contributions are covered.'
          custom-pr-sign-comment: 'The CLA has been signed successfully. Thank you for your contribution!'
          custom-allsigned-prcomment: 'All contributors have signed the CLA. ✅'
          lock-pullrequest-aftermerge: false
